% Usage: description_gui
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

%% Clean set, please don't change
db_clean=level1Study;

%%
if exist('fig1','var');
    if ishandle(fig1)
        close(fig1);
    end
end
fig1 = figure(...
    'Units','points', ...
    'Position',[50 50 800 600], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Study description', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');


% ---------- Study title:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.93 0.2 0.05], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Study title');
tit_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.94 0.2 0.05], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.studyTitle,...
    'Callback','db.studyTitle=strtrim(get(tit_stud,''String''));');

% ---------- Project folder:

if ~isfield(db.projectInfo,'projectPath')
    db.projectInfo.projectPath='';
end

project_stud=uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.57 0.94 0.15 0.05], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Project folder',...  
    'Callback','filepath=uigetdir(); if filepath ~=0; db.projectInfo.projectPath=filepath; set(projectset_stud,''String'',db.projectInfo.projectPath); end;');

projectset_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.75 0.94 0.2 0.05], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String',db.projectInfo.projectPath,... 
    'HorizontalAlignment','left',...
    'Callback','db.projectInfo.projectPath=strtrim(get(projectset_stud,''String''));');

projectset_help=uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.73 0.955 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=11; studyinfo'); 


% ---------- Short description:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.86 0.2 0.05], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Short description');
sdesc_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.87 0.7 0.05], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'HorizontalAlignment','left',...
    'String', db.studyShortDescription,...
    'Callback','db.studyShortDescription=strtrim(get(sdesc_stud,''String''));');


% ---------- Study description:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.79 0.2 0.05], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Full description');
fdesc_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.65 0.7 0.2], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'HorizontalAlignment','left',...
    'String', db.studyDescription,...
    'Callback','db.studyDescription=strtrim(tex_cat(get(fdesc_stud,''String'')));');

% ---------- Institutional Review Board

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.57 0.2 0.05], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'IRB');

irb_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.55 0.7 0.08], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'HorizontalAlignment','left',...
    'Max',[5],...
    'Min',[1],...
    'String', db.irbInfo,...
    'Callback','db.irbInfo=strtrim(tex_cat(get(irb_stud,''String'')));');

% ---------- Organization info:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.485 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Organization name');
forgz_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.41 0.2 0.12], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.organizationInfo.name,...
    'Callback','db.organizationInfo.name=strtrim(tex_cat(get(forgz_stud,''String'')));');

% ---------- Contact info:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.5 0.485 0.1 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Contact info');

fcont_name = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.63 0.49 0.32 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.contactInfo.name,...
    'Callback','db.contactInfo.name=strtrim(get(fcont_name,''String''));');  

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.5 0.445 0.1 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'phone');

fcont_phone = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.63 0.45 0.32 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.contactInfo.phone,...
    'Callback','db.contactInfo.phone=strtrim(get(fcont_phone,''String''));');  

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.5 0.405 0.1 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'email');

fcont_email = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.63 0.41 0.32 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.contactInfo.email,...
    'Callback','db.contactInfo.email=strtrim(get(fcont_email,''String''));');  



% ---------- Funding Organization info:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.345 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Funding organization');
ffund_stud = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.29 0.2 0.1], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.projectInfo.organization,...
    'Callback','db.projectInfo.organization=strtrim(tex_cat(get(ffund_stud,''String'')));');
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.5 0.345 0.1 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'GrantId');
ffund_grant_number = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.63 0.35 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.projectInfo.grantId,...
    'Callback','db.projectInfo.grantId=strtrim(get(ffund_grant_number,''String''));');  

% ---------- Experimenter:
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.03 0.225 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Experimenter');

exp_role = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.5 0.225 0.1 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Role');



for k=1:size(db.experimentersInfo,2)
exp_name_stud(k) = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.25 0.23-((k-1)*0.04) 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.experimentersInfo(k).name,...
    'Callback','for a=1:k; db.experimentersInfo(a).name=strtrim(get(exp_name_stud(a),''String'')); end');

exp_role_stud(k) = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.63 0.23-((k-1)*0.04) 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.experimentersInfo(k).role,...
    'Callback','for a=1:k; db.experimentersInfo(a).role=strtrim(get(exp_role_stud(a),''String'')); end');    
end


% Add an experimenter
exp_p = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.9 0.23 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '+',...
    'Callback','exp_plus');

% Delete an experimenter
exp_m = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.9 0.17 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '-',...
    'Callback','exp_minus');

% Next gui
exp_next = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.9 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Next',...
    'Callback','recording_gui');    

% Save study description in .mat file
exp_save = uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.9 0.09 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Save',...
    'Callback','save([db.projectInfo.projectPath ''\'' db.studyTitle ''.mat''],''db'');');    

%% Infobuttons
info_count=0;

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.955 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; studyinfo');

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.885 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; studyinfo');

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.815 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; studyinfo');

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.595 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=4; studyinfo');

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.5 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=5; studyinfo');

uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.61 0.5 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=6; studyinfo');
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.36 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=7; studyinfo');
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.61 0.36 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=8; studyinfo');
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.23 0.24 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=9; studyinfo');
uicontrol(...
    'Parent', fig1, ...
    'Units','normalized', 'Position', [0.61 0.24 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=10; studyinfo');

% eof
