% Usage: ess_start
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

clear;
clear global;

%% define database as global variable
global db;
%% Load Study description

fig0 = figure(...
    'Units','points', ...
    'Position',[400 300 300 200], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Open study description', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');

% load an empty study description new_study.mat 
% you can predefine text fields by editing new_study.mat and saving in the gui_func folder
% Hint: new_study.mat is read only, this needs to be changed before overwriting
new_study = uicontrol(...
    'Parent', fig0, ...
    'Units','normalized', 'Position', [0.2 0.7 0.6 0.15], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Create new study description',...
    'Callback','load(''new_study.mat''); close(fig0); description_gui;');

% load an existing .mat study description
loadmat_study = uicontrol(...
    'Parent', fig0, ...
    'Units','normalized', 'Position', [0.2 0.45 0.6 0.15], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Load .mat study description',...
    'Callback','[filename filepath]=uigetfile(''*.mat''); if filename ~=0; load(fullfile(filepath,filename)); close(fig0); description_gui; end;');

% load study description from xml file
loadxml_study = uicontrol(...
    'Parent', fig0, ...
    'Units','normalized', 'Position', [0.2 0.2 0.6 0.15], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Load .xml study description',...
    'Callback','[filename filepath]=uigetfile(''*.xml''); if filename ~=0; db=level1Study(fullfile(filepath,filename)); close(fig0); description_gui; end;');

% eof
