% Usage: recording_gui
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

type_item={'EEG','MEG','MoCap','Gaze'}; 
name_item={'Brainproducts','BioSemi','OptiTrack','SMI','Smarting'}; 
refloc_item={'Nose','Nasion','Cz','Average','Ears','Right Ear','Left Ear','Mastoids','Linked Mastoids','Right Mastoid','Left Mastoid','CMS','WCT'};
chanloctype_item={'10-20','10-10','10-5','EGI','Custom'};

type_item_length=length(type_item);
name_item_length=length(name_item);
refloc_item_length=length(refloc_item);
chanloctype_item_length=length(chanloctype_item);
if exist('fig2','var');
    if ishandle(fig2)
        close(fig2);
    end
end


fig2 = figure(...
    'Units','points', ...
    'Position',[50 50 800 600], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Recording parameter', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');


% ---------- Recording parameter set label:
uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.02 0.95 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Recording parameter set');
rpsl_stud = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25 0.95 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.recordingParameterSetLabel,...
    'Callback','db.recordingParameterSet.recordingParameterSetLabel=strtrim(get(rpsl_stud,''String''));');
rpsl_help=uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.96 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=15; recmodinfo');

% ---------- Recording configuration settings
recordsetpath=[];
recordsetfile=[];

if ~isfield(db.recordingParameterSet,'recConfig')
    db.recordingParameterSet.recConfig='';
end

recordset_stud=uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.48 0.95 0.2 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Rec. configuration file',...  
    'Callback','[recordsetfile recordsetpath]=uigetfile({''*.*''}); if recordsetfile ~=0; db.recordingParameterSet.recConfig=fullfile(recordsetpath,recordsetfile); set(recordset_stud,''String'',db.recordingParameterSet.recConfig);end;');

recordset_stud = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.71 0.95 0.27 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',db.recordingParameterSet.recConfig,... 
    'HorizontalAlignment','left',...
    'Callback','db.recordingParameterSet.recConfig=strtrim(get(recordset_stud,''String''));');

recordset_help=uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.69 0.96 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=14; recmodinfo'); 


% ---------- Modality description:
uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.85 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Modality');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.8 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Type');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.75 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Sampling rate');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.7 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Sensor device name');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.65 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Start channel');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.6 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'End channel');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.55 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Subject per session');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.5 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Reference location');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.45 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Reference label');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.4 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Channel location type');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.35 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Channel label');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.19 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'non Scalp channel label');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.03 0.08 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'description');

% Loop over modalities
for m=1:size(db.recordingParameterSet.modality,2)

mod_num(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.85 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', m);   

[tf]=ismember(db.recordingParameterSet.modality(m).type,type_item);
if tf == 0
    if isempty(db.recordingParameterSet.modality(m).type);
        db.recordingParameterSet.modality(m).type={' '};
    end
    type_item=[type_item(1:type_item_length) db.recordingParameterSet.modality(m).type];
end
type_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.8 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',type_item,...
    'HorizontalAlignment','center',...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).type=type_item{get(type_stud(a),''Value'')}; end');
    [tf, loc]=ismember(db.recordingParameterSet.modality(m).type,type_item);
    if loc ~= 0
    set(type_stud(m),'Value',loc)
    end

sr_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.75 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).samplingRate,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).samplingRate=strtrim(get(sr_stud(a),''String'')); end');

[tf]=ismember(db.recordingParameterSet.modality(m).name,name_item);
if tf == 0
    if isempty(db.recordingParameterSet.modality(m).name);
        db.recordingParameterSet.modality(m).name={' '};
    end
    name_item=[name_item(1:name_item_length) db.recordingParameterSet.modality(m).name];
end
name_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.7 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', name_item,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).name=name_item{get(name_stud(a),''Value'')}; end');
    [tf,loc]=ismember(db.recordingParameterSet.modality(m).name,name_item);
    if loc ~= 0
    set(name_stud(m),'Value',loc)
    end
    
startchannel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.65 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).startChannel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).startChannel=strtrim(get(startchannel_stud(a),''String'')); end');

endchannel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.6 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).endChannel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).endChannel=strtrim(get(endchannel_stud(a),''String'')); end');

sisn_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.55 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).subjectInSessionNumber,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).subjectInSessionNumber=strtrim(get(sisn_stud(a),''String'')); end');

[tf]=ismember(db.recordingParameterSet.modality(m).referenceLocation,refloc_item);
if tf == 0
    if isempty(db.recordingParameterSet.modality(m).referenceLocation);
        db.recordingParameterSet.modality(m).referenceLocation={' '};
    end
    refloc_item=[refloc_item(1:refloc_item_length) db.recordingParameterSet.modality(m).referenceLocation];
end
refloc_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.5 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', refloc_item,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).referenceLocation=refloc_item{get(refloc_stud(a),''Value'')}; end');
    [tf,loc]=ismember(db.recordingParameterSet.modality(m).referenceLocation,refloc_item);
    if loc ~= 0
    set(refloc_stud(m),'Value',loc)
    end
    
reflabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.45 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).referenceLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).referenceLabel=strtrim(get(reflabel_stud(a),''String'')); end');

[tf]=ismember(db.recordingParameterSet.modality(m).channelLocationType,chanloctype_item);
if tf == 0
    if isempty(db.recordingParameterSet.modality(m).channelLocationType);
        db.recordingParameterSet.modality(m).channelLocationType={' '};
    end
    chanloctype_item=[chanloctype_item(1:chanloctype_item_length) db.recordingParameterSet.modality(m).channelLocationType];
end
chanloctype_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.4 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', chanloctype_item,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).channelLocationType=chanloctype_item{get(chanloctype_stud(a),''Value'')}; end');
    [tf,loc]=ismember(db.recordingParameterSet.modality(m).channelLocationType,chanloctype_item);
    if loc ~= 0
    set(chanloctype_stud(m),'Value',loc)
    end
    
chanlabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.24 0.2 0.15], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).channelLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).channelLabel=strtrim(tex_cat(get(chanlabel_stud(a),''String''))); end');

nonscalpchanlabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.13 0.2 0.1], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).nonScalpChannelLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).nonScalpChannelLabel=strtrim(tex_cat(get(nonscalpchanlabel_stud(a),''String''))); end');

description_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.02 0.2 0.1], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).description,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).description=strtrim(tex_cat(get(description_stud(a),''String''))); end');
end

% Read channel labels from chanloc file
loc_stud = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.05 0.307 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Read',...
    'Callback','read_locs');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.1 0.30 0.07 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'apply to');

apply_loc = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.17 0.305 0.05 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String',[num2cell(1:m) ' '],...
    'Callback','if ismember((get(apply_loc,''Value'')),1:m)==1; db.recordingParameterSet.modality(get(apply_loc,''Value'')).channelLabel=str; set(chanlabel_stud(get(apply_loc,''Value'')),''String'',db.recordingParameterSet.modality(get(apply_loc,''Value'')).channelLabel); end; set(apply_loc,''Value'',m+1) ');
set(apply_loc,'Value',m+1);   

loc_stud = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.05 0.147 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Read',...
    'Callback','read_locs');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.1 0.14 0.07 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'apply to');

apply2_loc = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.17 0.145 0.05 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String',[num2cell(1:m) ' '],...
    'Callback','if ismember((get(apply2_loc,''Value'')),1:m)==1; db.recordingParameterSet.modality(get(apply2_loc,''Value'')).nonScalpChannelLabel=str; set(nonscalpchanlabel_stud(get(apply2_loc,''Value'')),''String'',db.recordingParameterSet.modality(get(apply2_loc,''Value'')).nonScalpChannelLabel); end; set(apply2_loc,''Value'',m+1); ');
set(apply2_loc,'Value',m+1);   

% Add a modality
mod_p = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.93 0.85 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '+',...
    'Callback','mod_plus');

% Delete a modality
mod_m = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.93 0.75 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '-',...
    'Callback','mod_minus');

% Next gui
mod_next = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.93 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Next',...
    'Callback','task_gui');

% Save study description in .mat file
exp_save = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.93 0.09 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Save',...
    'Callback','save([db.projectInfo.projectPath ''\'' db.studyTitle ''.mat''],''db'');');    
    
%% Infobuttons
info_count=0;

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.865 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; recmodinfo');  

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.815 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.76 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.715 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=4; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.665 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=5; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.615 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=6; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.565 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=7; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.515 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=8; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.465 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=9; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.415 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=10; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.365 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=11; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.205 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=12; recmodinfo');

uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.228 0.095 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=13; recmodinfo');

% eof