% Usage: session_gui
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

if exist('fig4','var');
    if ishandle(fig4)
        close(fig4);
    end
end

fig4 = figure(...
    'Units','points', ...
    'resize','on',...
    'Position',[50 50 900 600], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Session information', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');

taskLabel_item_length=size(db.tasksInfo,2);
taskLabel_item = [];
for n=1:taskLabel_item_length
    taskLabel_item{n}=db.tasksInfo(n).taskLabel;
end

session_tab_lim = max([ceil((size(db.sessionTaskInfo,2)+10)/20)]);
session_lim = 0.05/session_tab_lim;

session_panel1=uipanel('Parent',fig4,'Position',[0 0.1 1 0.77],'BackgroundColor', [0.8 0.8 0.8]);
session_panel2=uipanel('Parent',session_panel1,'Position',[0 (-session_tab_lim+1) 1 session_tab_lim],'BackgroundColor', [0.8 0.8 0.8]) ;
session_slider=uicontrol('Style','Slider','Parent',session_panel1,...
    'Units','normalized','Position',[0.98 0 0.02 1],...
    'Value',1,'Callback',{@slider_callback,session_panel2,session_tab_lim});



uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0 0.95 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Table of Session Information:');

% ---------- Table of session information:
uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.01 0.88 0.04 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Nr.');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.063 0.892 0.05 0.05], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Task label');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.12 0.883 0.05 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'LabId');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.17 0.88 0.08 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Subject');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.25 0.88 0.11 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Date');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.36 0.88 0.08 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Rec. set');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.44 0.88 0.18 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Event instance file');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.8 0.88 0.18 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Filename');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.62 0.88 0.18 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Original filename and path');

% Loop over sessions
for s=1:size(db.sessionTaskInfo,2)
    
    
    
    
    if size(db.sessionTaskInfo(s).dataRecording.startDateTime,2)<=1
        db.sessionTaskInfo(s).dataRecording.startDateTime=strtrim(datestr(now,'yyyymmddTHHMMSS'));
    end


session_num(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0 1-(s*session_lim) 0.05 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 14, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).sessionNumber,... 
    'Callback','for a=1:s; db.sessionTaskInfo(a).sessionNumber=strtrim(get(session_num(a),''String'')); end');

date_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.25 1-(s*session_lim) 0.11 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', datestr(datenum(db.sessionTaskInfo(s).dataRecording.startDateTime,'yyyymmddTHHMMSS'),'dd.mm.yyyy HH:MM:SS'),...
    'Callback','for a=1:s; db.sessionTaskInfo(a).dataRecording.startDateTime=datestr(datenum(strtrim(get(date_session(a),''String'')),''dd.mm.yyyy HH:MM:SS''),''yyyymmddTHHMMSS''); end');

[tf]=ismember(db.sessionTaskInfo(s).taskLabel,taskLabel_item);
if tf == 0
    if isempty(db.sessionTaskInfo(s).taskLabel);
        db.sessionTaskInfo(s).taskLabel={' '};
    end
    taskLabel_item=[taskLabel_item(1:taskLabel_item_length) db.sessionTaskInfo(s).taskLabel];
end
taskLabel_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.05 1-(s*session_lim) 0.07 session_lim], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',taskLabel_item,...
    'HorizontalAlignment','center',...
    'Callback','for a=1:s; db.sessionTaskInfo(a).taskLabel=taskLabel_item{get(taskLabel_session(a),''Value'')}; end');
    [tf, loc]=ismember(db.sessionTaskInfo(s).taskLabel,taskLabel_item);
    if loc ~= 0
    set(taskLabel_session(s),'Value',loc)
    end

labId_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.12 1-(s*session_lim) 0.05 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).labId,...
    'Callback','for a=1:s; db.sessionTaskInfo(a).labId=strtrim(get(labId_session(a),''String'')); end');

eventfile_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.44 1-(s*session_lim) 0.18 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).dataRecording.eventInstanceFile,...
    'Callback','for a=1:s; db.sessionTaskInfo(a).dataRecording.eventInstanceFile=strtrim(get(eventfile_session(a),''String'')); end');

file_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.8 1-(s*session_lim) 0.18 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).dataRecording.filename,...
    'Callback','for a=1:s; db.sessionTaskInfo(a).dataRecording.filename=strtrim(get(file_session(a),''String'')); end');

ofnap_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.62 1-(s*session_lim) 0.18 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).dataRecording.originalFileNameAndPath,...
    'Callback','for a=1:s; db.sessionTaskInfo(a).dataRecording.originalFileNameAndPath=strtrim(get(ofnap_session(a),''String'')); end');

rpsl_session(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.36 1-(s*session_lim) 0.08 session_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(s).dataRecording.recordingParameterSetLabel,...
    'Callback','for a=1:s; db.sessionTaskInfo(a).dataRecording.recordingParameterSetLabel=strtrim(get(rpsl_session(a),''String'')); end');

global sub_num;
global se;
global fig5; fig5=[];

sub_info(s) = uicontrol(...
    'Parent', session_panel2, ...
    'Units','normalized', 'Position', [0.17 1-(s*session_lim) 0.08 session_lim], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', sprintf('Subject %.0f',s),...
    'Callback',{@subject});

end

% ---------- recording file folder:
uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.005 0.03 0.15 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Recording file folder',...
    'Callback','filepath=uigetdir(); if filepath ~=0; db.rootURI=filepath; set(rootURI_session,''String'',db.rootURI); end;');

rootURI_session = uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.18 0.03 0.4 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.rootURI,...
    'Callback','db.rootURI=strtrim(get(rootURI_session,''String''));');

% Add a session
session_p = uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.87 0.95 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '+',...
    'Callback','session_plus');

% Delete a session
session_m = uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.93 0.95 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '-',...
    'Callback','session_minus');

% Next gui
session_next = uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.93 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'String', 'Next',...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'Callback','summary_gui');

% Save study description in .mat file
exp_save = uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.86 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Save',...
    'Callback','save([db.projectInfo.projectPath ''\'' db.studyTitle ''.mat''],''db'');');  
%% Infobuttons
info_count=0;

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.018 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; sessioninfo');  

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.295 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=5; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.077 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.136 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.515 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=7; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.7 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=8; sessioninfo');


uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.88 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=9; sessioninfo');


uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.39 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=6; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.2 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=4; sessioninfo');

uicontrol(...
    'Parent', fig4, ...
    'Units','normalized', 'Position', [0.16 0.04 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=10; sessioninfo');  

% eof
% Local Variables:
% time-stamp-pattern: "40/Updated:  <%2d %3b %:y %02H:%02M, %u>"
% End:
