% Usage: subject
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

function subject(h_object,event)
A=char(get(h_object,'String'));
C = regexp(A,'[0-9]');
global sub_num;
sub_num = str2num(A(C));
global se;
global db;
global fig5;

se.gender_item = {'F','M','X'}; 
se.hand_item = {'R','L','A'}; 
se.vision_item = {'Normal','CorrectedToNormal','Impaired'}; 
se.hearing_item = {'Normal','CorrectedToNormal','Impaired'}; 
se.gender_item_length=length(se.gender_item);
se.hand_item_length=length(se.hand_item);
se.vision_item_length=length(se.vision_item);
se.hearing_item_length=length(se.hearing_item);

if ishandle(fig5)
    close(fig5);
end

fig5 = figure(...
    'Units','points', ...
    'Position',[100 50 300 500], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', ['Subject ' num2str(sub_num)], ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');

% ---------- subject information:
s_labId = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.95 0.5 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String','SubjectId');

se.labId = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.95 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.labId,...
    'Callback','db.sessionTaskInfo(sub_num).subject.labId=strtrim(get(se.labId,''String''));');

s_channelLocations = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.9 0.5 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Channel locations');

se.channelLocations = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.9 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.channelLocations,...
    'Callback','db.sessionTaskInfo(sub_num).subject.channelLocations=strtrim(get(se.channelLocations,''String''));');

s_inSessionNumber = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.85 0.5 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'in Session number');

se.inSessionNumber = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.85 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.inSessionNumber,...
    'Callback','db.sessionTaskInfo(sub_num).subject.inSessionNumber=strtrim(get(se.inSessionNumber,''String''));');

s_group = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.8 0.23 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Group');

se.group = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.8 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.group,...
    'Callback','db.sessionTaskInfo(sub_num).subject.group=strtrim(get(se.group,''String''));');

s_gender = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.75 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Gender');

[tf]=ismember(db.sessionTaskInfo(sub_num).subject.gender,se.gender_item);
if tf == 0
    if isempty(db.sessionTaskInfo(sub_num).subject.gender);
        db.sessionTaskInfo(sub_num).subject.gender={' '};
    end
    se.gender_item=[se.gender_item(1:se.gender_item_length) db.sessionTaskInfo(sub_num).subject.gender];
end

se.gender = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.75 0.45 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', se.gender_item,...
    'Callback','db.sessionTaskInfo(sub_num).subject.gender=se.gender_item{get(se.gender,''Value'')};');
    [tf,loc]=ismember(db.sessionTaskInfo(sub_num).subject.gender,se.gender_item);
    if loc ~= 0
    set(se.gender,'Value',loc)
    end

s_YOB = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.7 0.21 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'YOB');

se.YOB = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.7 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.YOB,...
    'Callback','db.sessionTaskInfo(sub_num).subject.YOB=strtrim(get(se.YOB,''String''));');

s_age = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.65 0.21 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Age');

se.age = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.65 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.age,...
    'Callback','db.sessionTaskInfo(sub_num).subject.age=strtrim(get(se.age,''String''));');

s_hand = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.6 0.23 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Hand');

[tf]=ismember(db.sessionTaskInfo(sub_num).subject.hand,se.hand_item);
if tf == 0
    if isempty(db.sessionTaskInfo(sub_num).subject.hand);
        db.sessionTaskInfo(sub_num).subject.hand={' '};
    end
    se.hand_item=[se.hand_item(1:se.hand_item_length) db.sessionTaskInfo(sub_num).subject.hand];
end

se.hand = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.6 0.45 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', se.hand_item,...
    'Callback','db.sessionTaskInfo(sub_num).subject.hand=se.hand_item{get(se.hand,''Value'')};');
    [tf,loc]=ismember(db.sessionTaskInfo(sub_num).subject.hand,se.hand_item);
    if loc ~= 0
    set(se.hand,'Value',loc)
    end

s_vision = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.55 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Vision');

[tf]=ismember(db.sessionTaskInfo(sub_num).subject.vision,se.vision_item);
if tf == 0
    if isempty(db.sessionTaskInfo(sub_num).subject.vision);
        db.sessionTaskInfo(sub_num).subject.vision={' '};
    end
    se.vision_item=[se.vision_item(1:se.vision_item_length) db.sessionTaskInfo(sub_num).subject.vision];
end

se.vision = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.55 0.45 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', se.vision_item,...
    'Callback','db.sessionTaskInfo(sub_num).subject.vision=se.vision_item{get(se.vision,''Value'')};');
    [tf,loc]=ismember(db.sessionTaskInfo(sub_num).subject.vision,se.vision_item);
    if loc ~= 0
    set(se.vision,'Value',loc)
    end

s_hearing = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.5 0.28 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Hearing');

[tf]=ismember(db.sessionTaskInfo(sub_num).subject.hearing,se.hearing_item);
if tf == 0
    if isempty(db.sessionTaskInfo(sub_num).subject.hearing);
        db.sessionTaskInfo(sub_num).subject.hearing={' '};
    end
    se.hearing_item=[se.hearing_item(1:se.hearing_item_length) db.sessionTaskInfo(sub_num).subject.hearing];
end

se.hearing = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.5 0.45 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', se.hearing_item,...
    'Callback','db.sessionTaskInfo(sub_num).subject.hearing=se.hearing_item{get(se.hearing,''Value'')};');
    [tf,loc]=ismember(db.sessionTaskInfo(sub_num).subject.hearing,se.hearing_item);
    if loc ~= 0
    set(se.hearing,'Value',loc)
    end

s_height = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.45 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Height');

se.height = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.45 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.height,...
    'Callback','db.sessionTaskInfo(sub_num).subject.height=strtrim(get(se.height,''String''));');

s_weight = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.4 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Weight');

se.weight = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.4 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.weight,...
    'Callback','db.sessionTaskInfo(sub_num).subject.weight=strtrim(get(se.weight,''String''));');

s_caffeine = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.35 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Caffeine');

se.caffeine = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.35 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.medication.caffeine,...
    'Callback','db.sessionTaskInfo(sub_num).subject.medication.caffeine=strtrim(get(se.caffeine,''String''));');

s_alcohol = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.3 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Alcohol');

se.alcohol = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.3 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.medication.alcohol,...
    'Callback','db.sessionTaskInfo(sub_num).subject.medication.alcohol=strtrim(get(se.alcohol,''String''));');

s_capId = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.25 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'CapId');

se.capID = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.25 0.45 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.sessionTaskInfo(sub_num).subject.capId,...
    'Callback','db.sessionTaskInfo(sub_num).subject.capId=strtrim(get(se.capId,''String''));');

s_note= uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.03 0.2 0.25 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'HorizontalAlignment','left', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Note');

se.note = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.5 0.07 0.45 0.165], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'HorizontalAlignment','left', ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.sessionTaskInfo(sub_num).note,...
    'Callback','db.sessionTaskInfo(sub_num).note=strtrim(tex_cat(get(se.note,''String'')));');

% close subject
s_close = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.85 0.01 0.1 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'OK',...
    'Callback','delete(fig5);');
%% Infobuttons
info_count=0;

s_labId_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.95 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; subjectinfo');  

s_channelLocations_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.9 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; subjectinfo');

s_inSessionNumber_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.85 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; subjectinfo');

s_group_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.8 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=4; subjectinfo');

s_gender_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.75 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=5; subjectinfo');

s_YOB_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.7 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=6; subjectinfo');


s_age_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.65 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=7; subjectinfo');

s_hand_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.6 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=8; subjectinfo');

s_vision_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.55 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=9; subjectinfo');

s_hearing_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.5 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=10; subjectinfo');

s_height_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.45 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=11; subjectinfo');

s_weight_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.4 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=12; subjectinfo');

s_caffeine_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.35 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=13; subjectinfo');

s_alcohol_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.3 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=14; subjectinfo');

s_note_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.195 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=15; subjectinfo');

s_capId_info = uicontrol(...
    'Parent', fig5, ...
    'Units','normalized', 'Position', [0.445 0.25 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=16; subjectinfo');

% eof