% Usage: summary_gui
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

isInESSContainer_item={'Yes','No'};
allSubjectsHealthyAndNormal_item={'Yes','No'};

isInESSContainer_item_length=length(isInESSContainer_item);
allSubjectsHealthyAndNormal_item_length=length(allSubjectsHealthyAndNormal_item);

if exist('fig8','var');
    if ishandle(fig8)
        close(fig8);
    end
end

fig8 = figure(...
    'Units','points', ...
    'Position',[50 50 800 600], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Summary information', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0 0.95 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Summary Information:');

% ---------- Summary information:

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0 0.85 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'ESS file path');

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0 0.8 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Is in ESS container');

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0 0.6 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Subjects healthy and normal');

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.4 0.9 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'License type');

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.4 0.85 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'License text');

% ---------- Get ESS version:
essversionget_summary=uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.07 0.91 0.1 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'ESS version',...
    'Callback','db.essVersion=get_ess_versions;set(essversion_summary,''String'',db.essVersion);');
    
essversion_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.91 0.05 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.essVersion,...
    'Callback','db.essVersion=strtrim(get(essversion_summary,''String''));');   

% ---------- ESS file Path:
essFilePath_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.86 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.essFilePath,...
    'Callback','db.essFilePath=strtrim(get(essFilePath_summary,''String''));');

% ---------- Get size of data recording folder:
totalSizecalc_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.07 0.71 0.1 0.04], ...
    'Style', 'push', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Total size',...
    'Callback','Folderinfo=dir(db.rootURI);Foldersize=0;for n=1:size(Folderinfo,1);Foldersize=Foldersize+Folderinfo(n).bytes; end; db.summaryInfo.totalSize=sprintf(''%0.2f GB'',Foldersize*10^-9); set(totalSize_summary,''String'',db.summaryInfo.totalSize);');
    
totalSize_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.71 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.summaryInfo.totalSize,...
    'Callback','db.summaryInfo.totalSize=strtrim(get(totalSize_summary,''String''));');  

% ---------- License information:
licensetype_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.6 0.91 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...   
    'String', db.summaryInfo.license.type,...
    'Callback','db.summaryInfo.license.type=strtrim(get(licensetype_summary,''String''));');

licensetext_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.6 0.71 0.35 0.19], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.summaryInfo.license.text,... 
    'Max',[5],...
    'Min',[1],...
    'Callback','db.summaryInfo.license.text=strtrim(tex_cat(get(licensetext_summary,''String'')));');

% ---------- Is in ESS Container?:
[tf]=ismember(db.isInEssContainer,isInESSContainer_item);
if tf == 0
    if isempty(db.isInEssContainer);
        db.isInEssContainer={' '};
    end
    isInESSContainer_item=[isInESSContainer_item db.isInEssContainer];
end

isInESSContainer_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.805 0.05 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',isInESSContainer_item,...
    'HorizontalAlignment','center',...
    'Callback','db.isInEssContainer=isInESSContainer_item{get(isInESSContainer_summary,''Value'')};');
    [tf, loc]=ismember(db.isInEssContainer,isInESSContainer_item);
    if loc ~= 0
    set(isInESSContainer_summary,'Value',loc)
    end
    
% ---------- All subjects healthy and normal?:
[tf]=ismember(db.summaryInfo.allSubjectsHealthyAndNormal,allSubjectsHealthyAndNormal_item);
if tf == 0
    if isempty(db.isInEssContainer);
        db.summaryInfo.allSubjectsHealthyAndNormal={' '};
    end
    allSubjectsHealthyAndNormal_item=[allSubjectsHealthyAndNormal_item db.summaryInfo.allSubjectsHealthyAndNormal];
end

allSubjectsHealthyAndNormal_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.60 0.05 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',allSubjectsHealthyAndNormal_item,...
    'HorizontalAlignment','center',...
    'Callback','db.summaryInfo.allSubjectsHealthyAndNormal=allSubjectsHealthyAndNormal_item{get(allSubjectsHealthyAndNormal_summary,''Value'')};');
    [tf, loc]=ismember(db.summaryInfo.allSubjectsHealthyAndNormal,allSubjectsHealthyAndNormal_item);
    if loc ~= 0
    set(allSubjectsHealthyAndNormal_summary,'Value',loc)
    end

% Save study description in .mat file
exp_save = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.9 0.6 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Save',...
    'Callback','save([db.projectInfo.projectPath ''\'' db.studyTitle ''.mat''],''db'');');
%% Validation
validatetext=[];
validate_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.03 0.45 0.18 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Validate study',...
    'Callback','gui_validate');

validatetext_summary = uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.25 0.3 0.7 0.19], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String',validatetext,... 
    'HorizontalAlignment','left',...
    'Max',[5],...
    'Min',[1],...
    'Callback',' ');



%% Infobuttons
info_count=0;

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.92 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.82 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.575 0.92 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=4; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.575 0.87 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=5; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.72 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=6; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.615 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=7; summaryinfo');  

uicontrol(...
    'Parent', fig8, ...
    'Units','normalized', 'Position', [0.225 0.46 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=8; summaryinfo');  

% eof