% Usage: task_gui
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>


if exist('fig6','var');
    if ishandle(fig6)
        close(fig6);
    end
end

fig6 = figure(...
    'Units','points', ...
    'Position',[50 50 800 600], ...
    'Color', [0.8 0.8 0.8], ...
    'Name', 'Task information', ...
    'NumberTitle','off', ...
    'PaperUnits','points', ...
    'ToolBar','none', 'MenuBar','none');

task_tab_lim = max([ceil((size(db.tasksInfo,2)+5)/10)]);
task_lim = 0.1/task_tab_lim;

task_panel1=uipanel('Parent',fig6,'Position',[0 0.1 1 0.7],'BackgroundColor', [0.8 0.8 0.8]);
task_panel2=uipanel('Parent',task_panel1,'Position',[0 (-task_tab_lim+1) 1 task_tab_lim],'BackgroundColor', [0.8 0.8 0.8]) ;
task_slider=uicontrol('Style','Slider','Parent',task_panel1,...
    'Units','normalized','Position',[0.98 0 0.02 1],...
    'Value',1,'Callback',{@slider_callback,task_panel2,task_tab_lim});

% ---------- Table of Task information:
uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0 0.95 0.24 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Table of Task Information:');

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.01 0.825 0.05 0.05], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Task label');

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.07 0.8 0.4 0.05], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Tag');

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.48 0.8 0.51 0.05], ...
    'Style', 'text', ...
    'Fontsize', 12, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Description');

% Loop over tasks
for t=1:size(db.tasksInfo,2)
    
taskLabel_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0 1-(t*task_lim) 0.07 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).taskLabel,...
    'Callback','for a=1:t; db.tasksInfo(a).taskLabel=strtrim(get(taskLabel_task(a),''String'')); end');        

tag_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0.07 1-(t*task_lim) 0.4 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).tag,... 
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:t; db.tasksInfo(a).tag=strtrim(tex_cat(get(tag_task(a),''String''))); end');

description_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0.47 1-(t*task_lim) 0.51 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).description,...
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:t; db.tasksInfo(a).description=strtrim(tex_cat(get(description_task(a),''String''))); end');

end

% Add a task
task_p = uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.87 0.95 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '+',...
    'Callback','task_plus');

% Delete a task
task_m = uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.93 0.95 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', '-',...
    'Callback','task_minus');

% Next gui
task_next = uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.93 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'Next',...
    'Callback','event_gui');

% Save study description in .mat file
exp_save = uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.86 0.03 0.05 0.04], ...
    'Style', 'push', ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'Fontsize', 14, ...
    'String', 'Save',...
    'Callback','save([db.projectInfo.projectPath ''\'' db.studyTitle ''.mat''],''db'');');  
    
%% Infobuttons
info_count=0;

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.025 0.8 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=1; taskinfo');  

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.26 0.8 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=2; taskinfo');

uicontrol(...
    'Parent', fig6, ...
    'Units','normalized', 'Position', [0.725 0.8 0.02 0.02], ...
    'Style', 'push', ...
    'Fontsize', 10, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', 'i',...
    'Callback','info_count=3; taskinfo');

% eof