% Usage: event_plus
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

% Add a new event
e=e+1;
db.eventCodesInfo(e)=db_clean.eventCodesInfo(1);

code_event(e) = uicontrol(...
    'Parent', event_panel2, ...
    'Units','normalized', 'Position', [0 1-(e*event_lim) 0.07 event_lim], ...
    'Style', 'edit', ...
    'Fontsize', 12, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.eventCodesInfo(e).code,...
    'Callback','for a=1:e; db.eventCodesInfo(a).code=strtrim(get(code_event(a),''String'')); end');        

[tf]=ismember(db.eventCodesInfo(e).taskLabel,taskLabel_item);
if tf == 0
    if isempty(db.eventCodesInfo(e).taskLabel);
        db.eventCodesInfo(e).taskLabel={' '};
    end
    taskLabel_item=[taskLabel_item(1:taskLabel_item_length) db.eventCodesInfo(e).taskLabel];
end
taskLabel_event(e) = uicontrol(...
    'Parent', event_panel2, ...
    'Units','normalized', 'Position', [0.07 1-(e*event_lim) 0.07 event_lim], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',taskLabel_item,...
    'HorizontalAlignment','center',...
    'Callback','for a=1:e; db.eventCodesInfo(a).taskLabel=taskLabel_item{get(taskLabel_event(a),''Value'')}; end');
    [tf, loc]=ismember(db.eventCodesInfo(e).taskLabel,taskLabel_item);
    if loc ~= 0
    set(taskLabel_event(e),'Value',loc)
    end

label_event(e) = uicontrol(...
    'Parent', event_panel2, ...
    'Units','normalized', 'Position', [0.14 1-(e*event_lim) 0.12 event_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.eventCodesInfo(e).condition.label,...
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:e; db.eventCodesInfo(a).condition.label=strtrim(get(label_event(a),''String'')); end');        

description_event(e) = uicontrol(...
    'Parent', event_panel2, ...
    'Units','normalized', 'Position', [0.26 1-(e*event_lim) 0.36 event_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.eventCodesInfo(e).condition.description,...
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:e; db.eventCodesInfo(a).condition.description=strtrim(get(description_event(a),''String'')); end');

tag_event(e) = uicontrol(...
    'Parent', event_panel2, ...
    'Units','normalized', 'Position', [0.62 1-(e*event_lim) 0.36 event_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.eventCodesInfo(e).condition.tag,...
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:e; db.eventCodesInfo(a).condition.tag=strtrim(get(tag_event(a),''String'')); end');

% reload event_gui every 10th event to adapt event panel size
if mod(e,10)==0
    event_gui
    val=2/e;
    set(event_panel2,'Position',[0 (-event_tab_lim+1)*val 1 event_tab_lim])
    set(event_slider,'Value',val)
end

%eof 