% Usage: mod_plus
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

% Add a new modality
m=m+1;
  

if m<=3
    db.recordingParameterSet.modality(m)=db_clean.recordingParameterSet.modality(1);
    set(apply_loc,'String',[num2cell(1:m) ' '],'Value',m+1);    
    set(apply2_loc,'String',[num2cell(1:m) ' '],'Value',m+1);  
    
mod_num(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.85 0.2 0.04], ...
    'Style', 'text', ...
    'Fontsize', 14, ...
    'Backgroundcolor', [0.8 0.8 0.8], ...
    'String', m);   
        
type_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.8 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String',[type_item(1:type_item_length) ' '],...
    'Value',[type_item_length+1],...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).type=type_item{get(type_stud(a),''Value'')}; end');

sr_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.75 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).samplingRate,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).samplingRate=strtrim(get(sr_stud(a),''String'')); end');

name_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.7 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', [name_item(1:name_item_length) ' '],...
    'Value',[name_item_length+1],...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).name=name_item{get(name_stud(a),''Value'')}; end');

startchannel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.65 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).startChannel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).startChannel=strtrim(get(startchannel_stud(a),''String'')); end');

endchannel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.6 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).endChannel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).endChannel=strtrim(get(endchannel_stud(a),''String'')); end');

sisn_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.55 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).subjectInSessionNumber,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).subjectInSessionNumber=strtrim(get(sisn_stud(a),''String'')); end');

refloc_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.5 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', [refloc_item(1:refloc_item_length) ' '],...
    'Value',[refloc_item_length+1],...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).referenceLocation=refloc_item{get(refloc_stud(a),''Value'')}; end');

reflabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.45 0.2 0.04], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.recordingParameterSet.modality(m).referenceLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).referenceLabel=strtrim(get(reflabel_stud(a),''String'')); end');

chanloctype_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.4 0.2 0.04], ...
    'Style', 'popup', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', [chanloctype_item(1:chanloctype_item_length) ' '],...
    'Value',[chanloctype_item_length+1],...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).channelLocationType=chanloctype_item{get(chanloctype_stud(a),''Value'')}; end');

chanlabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.24 0.2 0.15], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).channelLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).channelLabel=strtrim(get(chanlabel_stud(a),''String'')); end');

nonscalpchanlabel_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.13 0.2 0.1], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).nonScalpChannelLabel,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).nonScalpChannelLabel=strtrim(get(nonscalpchanlabel_stud(a),''String'')); end');

description_stud(m) = uicontrol(...
    'Parent', fig2, ...
    'Units','normalized', 'Position', [0.25+((m-1)*0.23) 0.02 0.2 0.1], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'Max',[5],...
    'Min',[1],...
    'String', db.recordingParameterSet.modality(m).description,...
    'Callback','for a=1:m; db.recordingParameterSet.modality(a).description=strtrim(get(description_stud(a),''String'')); end');
else
    m=3;
end