% Usage: read_events
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

% get filename
filename=uigetfile({'*.xdf;*.vhdr;*.bdf;*.set'});

if filename~=0
    if exist('fig3','var');
        if ishandle(fig3)
            close(fig3);
        end
    end

    EEG=[];
    %load recording
    EEG=exp_eval(io_loadset(filename));
    %clear data
    EEG.data=[];
    %extract event codes
    codes=unique({EEG.event.type});


    fig3 = figure(...
        'Units','points', ...
        'Position',[500 300 300 300], ...
        'Color', [0.8 0.8 0.8], ...
        'Name', 'Read event codes', ...
        'NumberTitle','off', ...
        'PaperUnits','points', ...
        'ToolBar','none', 'MenuBar','none');


    uicontrol(...
        'Parent', fig3, ...
        'Units','normalized', 'Position', [0.05 0.05 0.9 0.9], ...
        'Style', 'text', ...
        'Fontsize', 12, ...
        'HorizontalAlignment','left',...
        'String',sprintf('Would you like to replace the event code information with these codes?\n%s',char(codes)'),...
        'Backgroundcolor', [0.8 0.8 0.8]);

    %if OK copy event codes in study schema and restart event_gui
    uicontrol(...
        'Parent', fig3, ...
        'Units','normalized', 'Position', [0.5 0.01 0.2 0.07], ...
        'Style', 'push', ...
        'Fontsize', 14, ...
        'Backgroundcolor', [0.8 0.8 0.8], ...
        'String', 'OK',...
        'Callback','close(fig3);for idx=e:-1:1; db.eventCodesInfo(idx)=[]; end; for idx=1:length(codes); db.eventCodesInfo(idx)=db_clean.eventCodesInfo(1); db.eventCodesInfo(idx).code=codes{idx}; end; event_gui;');

    %if Cancel close figure
    uicontrol(...
        'Parent', fig3, ...
        'Units','normalized', 'Position', [0.75 0.01 0.2 0.07], ...
        'Style', 'push', ...
        'Fontsize', 14, ...
        'Backgroundcolor', [0.8 0.8 0.8], ...
        'String', 'Cancel',...
        'Callback','close(fig3);');
end




