% Usage: task_plus
%
% Copyright (C) 2017, University of Oldenburg, Germany.
% Author : Manuela Jaeger M.Sc., manuela.jaeger@uni-oldenburg.de, Neuropsychology Lab, University of Oldenburg, Germany 
% Date   : 02.03.2017 
% Updated:  <>

% Add a new task
t=t+1;
db.tasksInfo(t)=db_clean.tasksInfo(1);


taskLabel_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0 1-(t*task_lim) 0.07 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).taskLabel,...
    'Callback','for a=1:t; db.tasksInfo(a).taskLabel=strtrim(get(taskLabel_task(a),''String'')); end');        

tag_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0.07 1-(t*task_lim) 0.4 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).tag,... 
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:t; db.tasksInfo(a).tag=strtrim(get(tag_task(a),''String'')); end');

description_task(t) = uicontrol(...
    'Parent', task_panel2, ...
    'Units','normalized', 'Position', [0.47 1-(t*task_lim) 0.51 task_lim], ...
    'Style', 'edit', ...
    'Fontsize', 10, ...
    'Foregroundcolor', [0 0 1], ...
    'String', db.tasksInfo(t).description,...
    'Max',[5],...
    'Min',[1],...
    'Callback','for a=1:t; db.tasksInfo(t).description=strtrim(get(description_task(a),''String'')); end');

% reload task_gui every 10th task to adapt task panel size
if mod(t,10)==0
    task_gui
    val=2/t;
    set(task_panel2,'Position',[0 (-task_tab_lim+1)*val 1 task_tab_lim])
    set(task_slider,'Value',val)
end

%eof